// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcal4q0YRG5-x0rk_1WbVHxKMvaRiAw60',
    appId: '1:643218556612:ios:fdca2422faed84d2b4ab91',
    messagingSenderId: '643218556612',
    projectId: 'comp3130-4a195',
    storageBucket: 'comp3130-4a195.appspot.com',
    iosBundleId: 'com.example.comp3130',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClCu2wg4M2VNAYhg3biUkMNe3Uhn5HLpo',
    appId: '1:643218556612:web:5a798b7d1c9d3f73b4ab91',
    messagingSenderId: '643218556612',
    projectId: 'comp3130-4a195',
    authDomain: 'comp3130-4a195.firebaseapp.com',
    storageBucket: 'comp3130-4a195.appspot.com',
    measurementId: 'G-SF00X7P293',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClCu2wg4M2VNAYhg3biUkMNe3Uhn5HLpo',
    appId: '1:643218556612:web:5a798b7d1c9d3f73b4ab91',
    messagingSenderId: '643218556612',
    projectId: 'comp3130-4a195',
    authDomain: 'comp3130-4a195.firebaseapp.com',
    storageBucket: 'comp3130-4a195.appspot.com',
    measurementId: 'G-SF00X7P293',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcal4q0YRG5-x0rk_1WbVHxKMvaRiAw60',
    appId: '1:643218556612:ios:fdca2422faed84d2b4ab91',
    messagingSenderId: '643218556612',
    projectId: 'comp3130-4a195',
    storageBucket: 'comp3130-4a195.appspot.com',
    iosBundleId: 'com.example.comp3130',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0POM0CWhKyQ_vFwJskAQxmtVTtFmrzkI',
    appId: '1:643218556612:android:c5d9f62e3efd8079b4ab91',
    messagingSenderId: '643218556612',
    projectId: 'comp3130-4a195',
    storageBucket: 'comp3130-4a195.appspot.com',
  );

}